# Multi-variable Linear Regression을 TensorFlow에서 구현

## Hypothesis using matrix

In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# Placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = "weight1")
w2 = tf.Variable(tf.random_normal([1]), name = "weight2")
w3 = tf.Variable(tf.random_normal([1]), name = "weight3")
b = tf.Variable(tf.random_normal([1]), name = "bias")

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

Instructions for updating:
Colocations handled automatically by placer.


### Full code

In [3]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]


# Placeholders for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = "weight1")
w2 = tf.Variable(tf.random_normal([1]), name = "weight2")
w3 = tf.Variable(tf.random_normal([1]), name = "weight3")
b = tf.Variable(tf.random_normal([1]), name = "bias")

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b


# Cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))


# Minimize - need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)


# Launch the graph in a session
sess = tf.Session()


# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  173961.17 
Prediction:
 [-220.77441 -258.69125 -258.3494  -281.34683 -195.59888]
10 Cost:  3.8482068 
Prediction:
 [148.19044 184.76633 178.60252 194.48209 142.64554]
20 Cost:  2.244556 
Prediction:
 [149.3124  186.10423 179.9263  195.92294 143.66399]
30 Cost:  2.2334461 
Prediction:
 [149.3214  186.10448 179.93205 195.92848 143.66214]
40 Cost:  2.2224352 
Prediction:
 [149.32698 186.10066 179.93378 195.92964 143.65721]
50 Cost:  2.2114441 
Prediction:
 [149.33257 186.09685 179.9355  195.93079 143.65227]
60 Cost:  2.2005413 
Prediction:
 [149.33812 186.09305 179.93723 195.93196 143.64735]
70 Cost:  2.1896966 
Prediction:
 [149.34366 186.08925 179.93892 195.93309 143.64246]
80 Cost:  2.1788867 
Prediction:
 [149.3492  186.08546 179.94063 195.93423 143.63756]
90 Cost:  2.1681552 
Prediction:
 [149.35474 186.08173 179.94235 195.9354  143.6327 ]
100 Cost:  2.1574833 
Prediction:
 [149.36021 186.07793 179.94403 195.9365  143.62784]
110 Cost:  2.1468687 
Prediction:
 [149.3657  186.

 [149.83772 185.75145 180.09145 196.0344  143.20683]
1100 Cost:  1.335007 
Prediction:
 [149.84193 185.7486  180.09274 196.03525 143.20314]
1110 Cost:  1.3288256 
Prediction:
 [149.84612 185.74571 180.09404 196.0361  143.19945]
1120 Cost:  1.3226892 
Prediction:
 [149.8503  185.74287 180.09534 196.03694 143.19579]
1130 Cost:  1.3165649 
Prediction:
 [149.85448 185.74002 180.09663 196.0378  143.19212]
1140 Cost:  1.3104807 
Prediction:
 [149.85864 185.73718 180.0979  196.03864 143.18848]
1150 Cost:  1.3044273 
Prediction:
 [149.8628  185.73434 180.0992  196.03949 143.18483]
1160 Cost:  1.298394 
Prediction:
 [149.86694 185.73152 180.10048 196.04033 143.18118]
1170 Cost:  1.2924216 
Prediction:
 [149.87106 185.72871 180.10176 196.04115 143.17757]
1180 Cost:  1.2864655 
Prediction:
 [149.87517 185.72589 180.10301 196.04199 143.17393]
1190 Cost:  1.2805583 
Prediction:
 [149.87926 185.72308 180.1043  196.04282 143.17033]
1200 Cost:  1.2746654 
Prediction:
 [149.88336 185.72029 180.10556 19

## Matrix

* __H(X) = XW__

### TensorFlow로 hypothesis 구현

In [4]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]


# Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")


# Hypothesis
hypothesis = tf.matmul(X, W) + b

### Full code

In [5]:
import tensorflow as tf
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]


# Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")


# Hypothesis
hypothesis = tf.matmul(X, W) + b


# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))


# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)


# Launch the graph in a session
sess = tf.Session()


# Initialize global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  559.3558 
Prediction:
 [[138.22731]
 [155.13478]
 [158.48157]
 [173.92145]
 [114.3476 ]]
10 Cost:  35.308853 
Prediction:
 [[158.45247]
 [179.48576]
 [182.4533 ]
 [200.02782]
 [132.9302 ]]
20 Cost:  35.123886 
Prediction:
 [[158.49165]
 [179.5746 ]
 [182.51917]
 [200.10132]
 [133.0069 ]]
30 Cost:  34.94469 
Prediction:
 [[158.46982]
 [179.59   ]
 [182.51271]
 [200.09607]
 [133.02753]]
40 Cost:  34.76647 
Prediction:
 [[158.44788]
 [179.60513]
 [182.5061 ]
 [200.0906 ]
 [133.04796]]
50 Cost:  34.589287 
Prediction:
 [[158.42598]
 [179.6202 ]
 [182.49947]
 [200.08513]
 [133.0683 ]]
60 Cost:  34.413006 
Prediction:
 [[158.40413]
 [179.63522]
 [182.49286]
 [200.07968]
 [133.0886 ]]
70 Cost:  34.237583 
Prediction:
 [[158.38235]
 [179.65022]
 [182.48627]
 [200.07423]
 [133.10886]]
80 Cost:  34.063225 
Prediction:
 [[158.36064]
 [179.66518]
 [182.47969]
 [200.06882]
 [133.12904]]
90 Cost:  33.88976 
Prediction:
 [[158.33899]
 [179.6801 ]
 [182.47316]
 [200.0634 ]
 [133.14919]]
100 C

1040 Cost:  21.026863 
Prediction:
 [[156.53065]
 [180.92616]
 [181.92719]
 [199.60536]
 [134.83769]]
1050 Cost:  20.923426 
Prediction:
 [[156.514  ]
 [180.93764]
 [181.92216]
 [199.60109]
 [134.85329]]
1060 Cost:  20.820496 
Prediction:
 [[156.49744]
 [180.9491 ]
 [181.91718]
 [199.59682]
 [134.86887]]
1070 Cost:  20.718195 
Prediction:
 [[156.4809 ]
 [180.96048]
 [181.91219]
 [199.59254]
 [134.88438]]
1080 Cost:  20.616364 
Prediction:
 [[156.46439]
 [180.97186]
 [181.90721]
 [199.5883 ]
 [134.89987]]
1090 Cost:  20.515202 
Prediction:
 [[156.44795]
 [180.9832 ]
 [181.90225]
 [199.58406]
 [134.9153 ]]
1100 Cost:  20.414438 
Prediction:
 [[156.43152]
 [180.9945 ]
 [181.89731]
 [199.5798 ]
 [134.9307 ]]
1110 Cost:  20.314337 
Prediction:
 [[156.41518]
 [181.00578]
 [181.89238]
 [199.5756 ]
 [134.94606]]
1120 Cost:  20.21467 
Prediction:
 [[156.39886]
 [181.01706]
 [181.88748]
 [199.57141]
 [134.9614 ]]
1130 Cost:  20.115602 
Prediction:
 [[156.38258]
 [181.02827]
 [181.88257]
 [199.56